# Generated by Django 6.0.3 on 2026-05-29 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='EscalaBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FIM_DE_SEMANA', 'Fim de Semana'), ('FERIADO', 'Feriado'), ('FERIADAO', 'Feriadão')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloco de Escala',
                'verbose_name_plural': 'Blocos de Escala',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Feriadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('manual', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feriadão',
                'verbose_name_plural': 'Feriadões',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('ESTADUAL', 'Estadual (Paraná)'), ('MUNICIPAL', 'Municipal (Curitiba)'), ('FACULTATIVO', 'Ponto Facultativo'), ('MANUAL', 'Manual / Empresa')], default='NACIONAL', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('recorrente', models.BooleanField(default=True, help_text='Repete todo ano')),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='GrupoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Grupo de Escala',
                'verbose_name_plural': 'Grupos de Escala',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EDICAO_DIA', 'Edição de dia'), ('TROCA_ESCALA', 'Troca de escala'), ('ADICAO_BLOQUEIO', 'Adição de bloqueio'), ('REMOCAO_BLOQUEIO', 'Remoção de bloqueio'), ('REGENERACAO', 'Regeneração da escala'), ('OUTRO', 'Outro')], max_length=25)),
                ('descricao', models.TextField()),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_alteracoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Histórico de Alterações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('fer_inicial', models.PositiveIntegerField(default=0, verbose_name='FER inicial')),
                ('pl_inicial', models.PositiveIntegerField(default=0, verbose_name='PL inicial')),
                ('total_s1', models.PositiveIntegerField(default=0)),
                ('total_s2', models.PositiveIntegerField(default=0)),
                ('total_dias_trabalhados', models.PositiveIntegerField(default=0)),
                ('total_dias_sobreaviso', models.PositiveIntegerField(default=0)),
                ('total_feriados', models.PositiveIntegerField(default=0)),
                ('total_feriadoes', models.PositiveIntegerField(default=0)),
                ('feriadao_s1_count', models.PositiveIntegerField(default=0)),
                ('feriadao_s2_count', models.PositiveIntegerField(default=0)),
                ('ultima_escala', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='escalas.grupoescala')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_escala', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Django')),
            ],
            options={
                'verbose_name': 'Usuário da Escala',
                'verbose_name_plural': 'Usuários da Escala',
                'ordering': ['grupo__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EscalaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('dia_util', models.BooleanField(default=True)),
                ('fim_de_semana', models.BooleanField(default=False)),
                ('feriado', models.BooleanField(default=False)),
                ('feriadao', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edicoes_escala', to=settings.AUTH_USER_MODEL)),
                ('s1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalas_s1', to='escalas.usuarioescala')),
                ('s2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalas_s2', to='escalas.usuarioescala')),
            ],
            options={
                'verbose_name': 'Dia da Escala',
                'verbose_name_plural': 'Dias da Escala',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERIAS', 'Férias'), ('FALTA', 'Falta'), ('TREINAMENTO', 'Treinamento'), ('LICENCA', 'Licença'), ('AFASTAMENTO', 'Afastamento'), ('INDISPONIBILIDADE', 'Indisponibilidade'), ('OUTRO', 'Outro')], default='FERIAS', max_length=25)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='escalas.usuarioescala')),
            ],
            options={
                'verbose_name': 'Bloqueio de Usuário',
                'verbose_name_plural': 'Bloqueios de Usuários',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
