# Generated by Django 6.0.3 on 2026-05-29 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEM_GRUPO_A', 'Sem usuário disponível no Grupo A'), ('SEM_GRUPO_B', 'Sem usuário disponível no Grupo B'), ('PROXIMO_FERIAS', 'Escala próxima a férias'), ('FERIADO_REPETIDO', 'Feriado/Feriadão repetido'), ('DESEQUILIBRIO', 'Desequilíbrio acima do limite'), ('MANUAL_IMPEDE', 'Escala manual impede redistribuição'), ('MES_FECHADO', 'Mês fechado bloqueou alteração'), ('OUTRO', 'Outro')], default='OUTRO', max_length=25)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta do Sistema',
                'verbose_name_plural': 'Alertas do Sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='escaladia',
            name='status',
            field=models.CharField(choices=[('AUTOMATICA', 'Automática'), ('MANUAL', 'Manual'), ('CONFIRMADA', 'Confirmada'), ('FECHADA', 'Fechada'), ('BLOQUEADA', 'Bloqueada')], default='AUTOMATICA', max_length=20),
        ),
        migrations.CreateModel(
            name='MesFechado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('status', models.CharField(choices=[('FECHADO', 'Fechado'), ('BLOQUEADO', 'Bloqueado')], default='FECHADO', max_length=20)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meses_fechados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mês Fechado',
                'verbose_name_plural': 'Meses Fechados',
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('ano', 'mes'), name='unique_mes_fechado')],
            },
        ),
    ]
