# Generated by Django 6.0.3 on 2026-06-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0002_alertasistema_escaladia_status_mesfechado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioescala',
            name='codigo_legado',
            field=models.CharField(blank=True, max_length=30, verbose_name='Codigo legado'),
        ),
        migrations.AddField(
            model_name='usuarioescala',
            name='lotacao',
            field=models.CharField(blank=True, max_length=40, verbose_name='Lotacao'),
        ),
        migrations.AddField(
            model_name='usuarioescala',
            name='oportunidades_iniciais',
            field=models.PositiveIntegerField(default=0, verbose_name='Oportunidades ate o corte'),
        ),
        migrations.AddField(
            model_name='usuarioescala',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarioescala',
            name='pl_inicial',
            field=models.PositiveIntegerField(default=0, verbose_name='PL ate o corte'),
        ),
    ]
