# Generated by Django 6.0.3 on 2026-07-10 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0003_usuarioescala_codigo_legado_usuarioescala_lotacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE_DESTINO', 'Aguardando gerente destino'), ('RECUSADA_DESTINO', 'Recusada pelo gerente destino'), ('PENDENTE_ADMIN', 'Aguardando aprovacao do administrador'), ('APROVADA', 'Aprovada'), ('REJEITADA_ADMIN', 'Rejeitada pelo administrador'), ('CANCELADA', 'Cancelada')], default='PENDENTE_DESTINO', max_length=30)),
                ('resposta_destino', models.TextField(blank=True)),
                ('destino_respondido_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_admin', models.TextField(blank=True)),
                ('admin_respondido_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_troca_respondidas_admin', to=settings.AUTH_USER_MODEL)),
                ('destino_respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_troca_respondidas_destino', to=settings.AUTH_USER_MODEL)),
                ('escala_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_troca_destino', to='escalas.escaladia')),
                ('escala_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_troca_origem', to='escalas.escaladia')),
                ('gerente_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_troca_destino', to='escalas.usuarioescala')),
                ('gerente_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_troca_origem', to='escalas.usuarioescala')),
                ('gerente_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_troca_solicitante', to='escalas.usuarioescala')),
                ('solicitante_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_troca_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitacao de Troca',
                'verbose_name_plural': 'Solicitacoes de Troca',
                'ordering': ['-created_at'],
            },
        ),
    ]
